### ISSUE TITLE
Allow multiple associated testimonials.

### ISSUE THREAD

**Issue by emzo** [woothemes/projects#100]
It's great that you can link a Testimonial to a Project, but there are many cases where you may want to have multiple testimonials associated with a single project.

I noticed in issue #84 (integration with the Our Team plugin) it mentions associating multiple team members with a project. I wonder if it might be worth creating a more general purpose way of associating post types with one another (be it one-to-one, one-to-many or many-to-many) that could be reused in a number of WooThemes plugins - could be used for the up-sell/cross-sell functionality in WooCommerce for example.

Or maybe we make the Projects plugin simpler by stripping out the Testimonials feature from the plugin and relying on something like Related Posts for WordPress by @barrykooij or Posts 2 Posts by @scribu for creating these relationships between post types.

**Comment by jeffikus** [comment]
Closing this for now, we can revisit at a later staff as an extension. @danieldudzic can you keep your repo open and mark as enhancement?

**Comment by danieldudzic** [comment]
@jeffikus Sounds good. What exactly should I mark as an enhancement, though?

**Comment by jeffikus** [comment]
@danieldudzic I think what we can do is to have a coffee chat at the GM in October and can decide the way forward if you keen?

**Comment by danieldudzic** [comment]
@jeffikus Sounds good. Looking forward to the GM :)

**Comment by mackaaij** [comment]
Any news on this guys? A new GM might be coming up :)
