### ISSUE TITLE
Add a dismis link to the admin notice

### ISSUE THREAD

**Issue by dwainm** [woothemes/projects#103]
When installing the plugin it shows a notice:
Projects by WooThemes is almost ready. To get started, configure your projects page.

There is no way to dismiss this notice, not even by a hook or admin css. Please add a link or alternative option here.

**Comment by jeffikus** [comment]
Cool cool - at conf today, will tackle in the morning tomorrow, I've set aside some non-flexslider time tomorrow :)

**Comment by mattyza** [comment]
I'd vote against a dismiss notice here.

This notice style is intended for setup steps which are required and unavoidable for using the plugin.

@jeffikus your thoughts?

**Comment by jeffikus** [comment]
That actually makes sense, happy to close.

**Comment by dwainm** [comment]
@jeffikus @mattyza,  My other suggestion was add a class to the notice. I know personally if I use the plugin in another way without the projects page I would want to remove it. Please consider this again, maybe a different solution, but please allow the user to remove this if they so desire :)

**Comment by jeffikus** [comment]
@dwainm please submit a pull request for this otherwise im gonna close again.

**Comment by dwainm** [comment]
Hey @jeffikus probably wont get to this any time soon. Best we close it unless some one else wants to submit a PR.

**Comment by jeffikus** [comment]
Thanks @dwainm
