### ISSUE TITLE
NEW IDEA: To get projects of portfolio post type on portfolio page.

### ISSUE THREAD

**Issue by abouolia** [woothemes/projects#104]
I know the `projects` plugin even `WooCommerce` when open portfolio page the page redirects to `?post_type=projects` to get projects using main query but i think this bad idea because this not static page other words the page lose page ID so that i have different idea to get projects on the static page with retention the `?page_id=2` the idea depends alter the main WP_Query of the WordPress to get projects on any static page.

In this link i wrote code about alter main query.

https://gist.github.com/abouolia/34defada8038aae8a214

I tested my code and the result was perfect.

i'm waiting some criticisms and comments.

**Comment by jeffikus** [comment]
Hi there

Thanks, I'll check this out tomorrow!

Jeff

**Comment by jeffikus** [comment]
Hi there

Thanks for the suggestion, that's a bit overkill to be honest - I'm glad it works for you, but I don't think it will apply to the majority of users. I'll keep the gist in my snippet library in case it does come up again.

Thanks for submitting!
