### ISSUE TITLE
exclude_categories in shortcode also excludes subcategories

### ISSUE THREAD

**Issue by TinyGiantStudios** [woothemes/projects#105]
Link to ticket: https://woothemes.zendesk.com/agent/tickets/270926

When using *exclude_categories* paramater in the projects shortcode, it will also prevent the sub-categories of the included ID's from displaying.

Example:
Main Cat 1: ID = 30
-- Child Cat 1: ID = 38
Main Cat 2: ID = 31
Main Cat 2: ID = 33

When using the shortcode:

```
[projects limit="12" columns="4" orderby="date" order="desc" exclude_categories="30,31,32"]
```

It will also hide the category with ID "38".

**Comment by jeffikus** [comment]
Fair enough, the taxonomy query has a param called include_children, see -> https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters that defaults to true. I'll add an extra option for this later this week. Let's say by Friday?

**Comment by jeffikus** [comment]
@TinyGiantStudios can you please grab that branch and give me some testing feedback please?

Here is an example use of the shortcode:
```
[projects limit="12" columns="4" orderby="date" order="desc" exclude_categories="71" include_children="false"]
```
include_children="false" will mean that the children of 71 will not be excluded and will be output on the frontend.

**Comment by TinyGiantStudios** [comment]
Yep, testing looks good this side! Thanks for the super quick turnaround time...
