### ISSUE TITLE
Add Projects Gallery Images Link Doesn't Work on New Projects

### ISSUE THREAD

**Issue by DustinHartzler** [woothemes/projects#109]
Project galleries can only be added once a post has been saved/published.

When trying to add Project Gallery Images
![](https://cldup.com/zoudP5e_Pn.png)

The screen briefly flashes from:
http://woo.dev/wp-admin/post-new.php?post_type=project

to: http://woo.dev/wp-admin/post-new.php?post_type=project#

Once the page has been saved as a draft or published, adding galleries works as expected.

**Comment by badcat** [comment]
I've had the same issue.

**Comment by DustinHartzler** [comment]
Ping. Any update?

**Comment by corvannoorloos** [comment]
I believe directly adding
```js
var attachment_image = attachment.sizes && attachment.sizes.thumbnail ? attachment.sizes.thumbnail.url : attachment.url;
```
after
```js
attachment_ids = attachment_ids ? attachment_ids + ',' + attachment.id : attachment.id;
```
in `projects/assets/js/admin.js` should solve this.

**Comment by Kenshino** [comment]
I just faced this issue.

https://github.com/woothemes/projects/pull/111 should fix your problems :)

**Comment by DustinHartzler** [comment]
Any update on when this will be released?

**Comment by jeffikus** [comment]
@DustinHartzler this week Thursday is final day of dev, so within the next week :dancer: I've updated the 1.5.0 milestone.
