### ISSUE TITLE
Embedded images in content auto-included at top

### ISSUE THREAD

**Issue by RiaanKnoetze** [woothemes/projects#121]
Link to ticket: 413624-zd-woothemes

When adding media to the main description of the project, that media will automatically be displayed at the top of the single project page on the front end.

Screenshots:
- Frontend: http://cld.wthms.co/1j0JY/5ataN7P9
- Backend: http://cld.wthms.co/10l5G/3gFLiuiO

I have tested this locally on the following themes with the same result:
- Canvas
- Storefront
- One Pager
- Twenty Sixteen

**Comment by RiaanKnoetze** [comment]
@jeffikus Any thoughts on this?

**Comment by jeffikus** [comment]
@RiaanKnoetze i'm not going to get to this today, earliest tomorrow.

**Comment by RiaanKnoetze** [comment]
Hey @jeffikus - Did you end up looking into this?

**Comment by jeffikus** [comment]
Oh yeah, I did :) pinging you in slack.

**Comment by jeffikus** [comment]
Ok, so as we discussed, this is an education thing.

If the user wants to upload an image into the content area and NOT have it in the gallery area, the image must not be attached to the post. This is done by first uploading the image into the Media Library and then inserted into the post content area.

Thanks for helping figure this issue out! @RiaanKnoetze
