### ISSUE TITLE
Gallery Suggestion?

### ISSUE THREAD

**Issue by badcat** [woothemes/projects#123]
Is there a recommended plugin to add so that galleries look decent and make sense in a Woo Project?

**Comment by RiaanKnoetze** [comment]
@badcat - Care to elaborate on what you mean by "look decent"? By default, these items are usually handled through the themes' CSS.

**Comment by badcat** [comment]
Sure - Fair enough "look decent" is subjective  :)  

Was looking for a suggestion of a plugin to intergrate with Woo Projects and enhance the (responsive) layout of the gallery images.

Since Projects doesn't seem to allow access to the basic WordPress Gallery Settings, I miss features like:
- Link To
- Columns
- Random Order
- Size

Since there are alreay plenty of plugins that hook into the WP gallery, I thought maybe there was one you could recommend to hook into your version of the gallery.

![default-gallery](https://cloud.githubusercontent.com/assets/26096/17668060/a5f82206-62d5-11e6-89b2-cd7adea5640d.png)
